services:
  my-server:
    ports:
      - 8080:8080
    depends_on:
      my-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./shared_logs:/app/shared_logs
    environment:
      LOG_PATH: /app/shared_logs/user-actions.json
      ML_API_PATH: ${ML_PATH}/api/PJA/stats/generate
      LOG_DIR: /app/shared_logs

  my-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      retries: 10

  my-cache-server:
    image: redis:7
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10