name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: .env 디렉토리 삭제 (기존에 있던 디렉토리 제거)
        run: rm -rf PJA/.env

      - name: .env 파일 만들기
        run: printf "%s" "${{ secrets.DOT_ENV }}" > PJA/.env

      - name: Gradlew 실행 권한 주기
        run: cd PJA && chmod +x ./gradlew

      - name: 테스트 및 빌드하기
        run: cd PJA && ./gradlew clean build -x test

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: .env 파일 EC2에 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "PJA/.env"
          target: "/home/${{ secrets.EC2_USERNAME }}/"

      - name: docker-compose.yml EC2에 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "PJA/docker-compose.yml"
          target: "/home/${{ secrets.EC2_USERNAME }}/"

      - name: Docker 이미지 생성
        run: docker build -t pja-server ./PJA

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag pja-server ${{ steps.login-ecr.outputs.registry }}/pja-server:latest

      - name: ECR에 Docker 이미지 Push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/pja-server:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            cd /home/${{ secrets.EC2_USERNAME }}/PJA
            docker compose down || true
            docker compose pull
            docker compose up --build -d